Output init.gif

Set Shell "bash"
Set Width 1200
Set Height 1200
Set FontSize 32
Set PlaybackSpeed 1.0
Set Framerate 60
Set TypingSpeed 50ms

Sleep 2s

Type "minepack init" Sleep 500ms  Enter
Sleep 1s
Type "testProject" Sleep 500ms Enter
Sleep 0.5s
Type "hiiiii" Sleep 500ms Enter
Sleep 1s
Type "myself" Sleep 500ms Enter
Wait /ctrl\+e complete.+/
Sleep 1s
Type "1.20.1" Sleep 500ms Enter
Wait /↑ up • ↓ down.+/
Sleep 2s
Enter
Sleep 1s
Enter
Sleep 1s
Left Sleep 500ms Enter
Sleep 5s  
