Output link.gif

Set Shell "bash"
Set Width 1200
Set Height 1200
Set FontSize 32

Sleep 2s
Hide
Type "cd testProject" Sleep 500ms Enter
Type "clear" Sleep 500ms Enter
Sleep 1s
Show

Type "minepack link add ./.minecraft/" Sleep 500ms Enter
Sleep 500ms Enter
Sleep 2s
Type "minepack link update" Sleep 500ms Enter
Sleep 1s
Left Sleep 1s Enter
Wait
Sleep 2s
Enter Sleep 1s
Type "ls ./.minecraft/mods" Sleep 500ms Enter
Sleep 5s