Output versionRevert.gif

Set Shell "bash"
Set Width 1400
Set Height 900
Set FontSize 32

Hide
Type "cd testProject" Sleep 500ms Enter
Type "clear" Sleep 500ms Enter
Sleep 1s
Show

Sleep 3s

Type "minepack version show --history" Sleep 500ms Enter
Sleep 3s

Type "minepack list" Sleep 500ms Enter
Sleep 3s

Type "minepack version jump 1" Sleep 500ms Enter
Sleep 1s

Type "minepack version show" Sleep 500ms Enter
Sleep 2s

Type "minepack list" Sleep 500ms Enter
Sleep 8s
