name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build all binaries
        run: bun compile:all

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: minepack-binaries
          path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: minepack-binaries
          path: build

      - name: Upload binaries to existing GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          # Do not set 'body' or 'generate_release_notes' so manual changelog is preserved
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
